### PR TITLE
Extend #contribute Slack channel

### PR DESCRIPTION
**Pull request by Relequestual**
After some discussion on the JSON Schema Slack server, we agreed we were using the new `#tsc-discussion` channel for things that weren't specifically linked to the TSC (Technical Steering Committee), and were treating it similar to how we previoulsy treated the old `#collaborators` channel, sharing updates about things which should be public and elsewhere.

Those of us in the discussion agreed we could repurpose the `#contribute` channel, to include discussions and updates about anything we wanted to share related to JSON Schema work.

**Please review the PR commit by commit.**

The first commit just reorders the JSON object keys in alphabetical order because I couldn't determine a logical place to add a new channel definition. Now there is logic! (Found a [VSCode plugin](https://marketplace.visualstudio.com/items?itemName=richie5um2.vscode-sort-json))

The second commit is a rename of the `#community` channel to `#community-mgmt`, which didn't get actioned here.

The third commit is that most important to and the primary topic of this PR, modifying the `#contribute` channel topic to be broader in scope.

### CODE REVIEW

**Review by benjagm — APPROVED** [review]

**Comment by Relequestual** [comment]
Need to update "other channels" file... oops.

**Review by Julian — APPROVED** [review]
I'm OK with this personally -- though I thought @gregsdennis was saying he preferred expanding the scope of one of the other two? But if he's good, I'm good :)

**Comment by gregsdennis** [comment]
I'm okay with this. However the topic at hand that spurred this change was implementer engagement, which doesn't really have a place.

Again, that's not questions about implementing (#implementers) or contributing to the JSON Schema project (#contribute).  Maybe it should have just gone in #general.

**Comment by Relequestual** [comment]
"JSON Schema project" emcompasses everything we do.

> ... implementer engagement, which doesn't really have a place.

You don't think that belongs in `#community-mgmt`? Implementers are part of the community.

**Comment by gregsdennis** [comment]
> You don't think that belongs in #community-mgmt? Implementers are part of the community.

That's where I was suggesting it go, but then it was argued that that channel was more "meta": _how_ we manage it.

I don't know. It's not as big a deal as this has become.

**Review by gregsdennis — APPROVED** [review]

**Pull request merged**
