### PR TITLE
Send notifications of failed GitHub actions to a new channel on Slack

### LINKED ISSUE #638: Send notifications of failed GitHub actions to a new channel on Slack.
## Context
The JSON Schema community has been growing rapidly in recent years, and as a result, our community operations have become more complex. While we've made strides in improving our processes and communication, there is always room for improvement. To that end, We'd like to start a discussion around identifying suitable automations that could help us to focus on generating value for JSON Schema.

## Requirements
We'd like to notify in the github slack channel when Github actions fails.

### PR DESCRIPTION
**Pull request by utnim2**
**GitHub Issue:**  #638 
Fixes #638  

**Summary**:
Added a new workflow for sending a message to the channel `#github` when there is a failed action

### CODE REVIEW

**Comment by benjagm** [comment]
@Min2who As we have been insisting, everyone needs to follow the triage process and make sure the issue is available and they have been assigned. I am going to close this PR to make sure we follow the process.

**Comment by Min2who** [comment]
> @Min2who As we have been insisting, everyone needs to follow the triage process and make sure the issue is available and they have been assigned. I am going to close this PR to make sure we follow the process.

@benjagm was this issue not available i dont get it

**Comment by benjagm** [comment]
Status available means it has the label "Status: Available" which is not the case, and also you need to make sure you discussed with the maintainer to be assigned on the comments of the issue as well.

We need to be good Open Source citizens, be respective with the rules and processes of the community and give everyone the same opportunities to get involved.

I made this communication in Slack specifically to avoid this type of sitations.
https://json-schema.slack.com/archives/C04MVQSRBRS/p1708678980924239

**Review by benjagm — APPROVED** [review]
Excellent job with this one @utnim2 !!

**Pull request merged**
