### PR TITLE
New github action to close OCWM with all tasks completed

### PR DESCRIPTION
**Pull request by benjagm**
This is a github action to close opened OCWM issues without pending tasks (all tasks completed or not tasks assigned at all). Intended to run in a weekly basis.

### CODE REVIEW

**Review by Relequestual — CHANGES_REQUESTED** [review]
We can use envrionment variables for owner and repo, removing the need to do the regex for each three times.
https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables

**Comment by benjagm** [comment]
> We can use envrionment variables for owner and repo, removing the need to do the regex for each three times. https://docs.github.com/en/actions/learn-github-actions/variables#default-environment-variables

Thanks Ben. I just updated the action with better management of environment variables.

**Review by gregsdennis — APPROVED** [review]

**Review by Relequestual — APPROVED** [review]
Eyeballed but not tested. Looks OK.

**Comment by Relequestual** [comment]
Thanks for your work on this!

**Pull request merged**
