### PR TITLE
Update ambassadors.json

### PR DESCRIPTION
**Pull request by paras3c**
These are my details for the position of JSON Schema Ambassador Program.

**GitHub Issue:** # / NA

**Summary**:

**Do you think resolving this issue might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**

Yes/No
[JUSTIFICATION]

### CODE REVIEW

**Review by benjagm — COMMENTED** [review]
Hi @paras3c! Thanks a lot for your interest. The Ambassadors Program is targeting mainly JSON Schema experts and after reviewing your application and contributions we don't think your content is JSON Schema specific to be considered for this specific program. Do you have JSON Schema specific content?

**Comment by benjagm** [comment]
@paras3c Did you have the chance to review my last comments?

**Comment by paras3c** [comment]
Hey @benjagm , sorry for replying late. I’m having my final semester examinations that’s why I’m keeping myself away from the internet for a while. However, currently I don’t have any json schema specific content but I can assure you that I’ll be making json schema specific contents as soon as I get accepted

**Comment by benjagm** [comment]
Hi Paras3c. This program is more focused in expert users rather than new users so I think Ambassadors as it is is not the best option for you to get involved with the Community. You can submit blog posts or contribute to some of the repositories instead and I think that will have a better fit for you.

**Comment by benjagm** [comment]
Thanks a lot for your interest @paras3c!! It means a lot for us but as stated in my previous comment, we think other types of programs will be a better option for you.

**Pull request closed without merging**
