### PR TITLE
Template to announce implementations

### PR DESCRIPTION
**Pull request by benjagm**
**GitHub Issue:** # / NA

**Summary**: Add a template to promote new implementations added to the Implementations page.

**Do you think resolving this issue might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**

No

### CODE REVIEW

**Review by Relequestual — CHANGES_REQUESTED** [review]
Nitpick, but should this file just be `templates.md` in the folder one level up? It contains multiple templates in one file (which I think is the right thing to do).

`adopters` also looks like it needs updating in the same way.

Otherwise, this looks great. Thanks for doing this work.

**Comment by benjagm** [comment]
> Nitpick, but should this file just be `templates.md` in the folder one level up? It contains multiple templates in one file (which I think is the right thing to do).

I think is better one single file with all the promotion messages.  What I can do is rename the file from tweet-template.md to promotion-template.md or promotion-templates.md

**Comment by Relequestual** [comment]
I agree that one file is best. I just think the name of the file needs to change.
Agreed =]

**Comment by benjagm** [comment]
> I agree that one file is best. I just think the name of the file needs to change.

I renamed all the templates for all the programs.

**Comment by benjagm** [comment]
> Nitpick, but should this file just be `templates.md` in the folder one level up? It contains multiple templates in one file (which I think is the right thing to do).
> 
> `adopters` also looks like it needs updating in the same way.
> 
> Otherwise, this looks great. Thanks for doing this work.

Done.

**Pull request merged**
