### PR TITLE
Add Juan Cruz Viotti to ambassador list

### PR DESCRIPTION
**Pull request by jviotti**
Not sure if I'm missing anything, but please let me know. Does things like AlterSchema and Learn JSON Schema count?

### CODE REVIEW

**Comment by Relequestual** [comment]
> Not sure if I'm missing anything, but please let me know. Does things like AlterSchema and Learn JSON Schema count?

Yes, they very much count =]

**Review by Relequestual — APPROVED** [review]
So pleased to formally recognise the work you do and the effort you've put into supporting JSON Schema!

**Comment by jviotti** [comment]
Thanks a lot! ❤️ 

> Yes, they very much count =]

@Relequestual Should I add them to this PR?

**Comment by jviotti** [comment]
I added them in case you want to re-review

**Review by benjagm — APPROVED** [review]
Thanks Juan!!

**Comment by benjagm** [comment]
Hi @jviotti . Can you please resolve the conflict? We'll merge this asap.

**Comment by jviotti** [comment]
Done @benjagm !

**Comment by jviotti** [comment]
Looks like the original JSON, even before this PR, is invalid? Let me fix it here

**Comment by jviotti** [comment]
OK @benjagm I also found the previous ambassador entry was not valid according to the schema you had in there. It should be all fixed now

**Pull request merged**
