### PR TITLE
Fixes Bug -  Action to send Community Meeting reminders failed

### PR DESCRIPTION
**Pull request by aialok**
**GitHub Issue:** #640 
Fixes : #640 

**Summary**:
-After trying to run using CommonJS, I encountered the same error that our workflow throws. However, after switching to ESM, it is working fine.
```
Earlier :
 const octokit = require('@octokit/core').Octokit;
          const mygithub = new octokit({
Latest : 
import { Octokit } from "@octokit/core";
          const mygithub = new Octokit({
```
- We need to run our workflow manually to check whether it is working fine or not.

**Do you think resolving this issue might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**

Yes/No
[JUSTIFICATION]

### CODE REVIEW

**Comment by benjagm** [comment]
Have you executed this in your fork?

**Comment by aialok** [comment]
@benjagm, please run the workflow manually once.
I noticed a similar problem with reminders in other workflows as well. If this solution works, we can apply it there too; otherwise, we might encounter errors there as well.

Thank you  : )

**Comment by aialok** [comment]
> Have you executed this in your fork?

Basically I need to token, and secrets and also I need to setup webhook for slack.
But I tried running different script and got the same error as this when commonjs is used while esm is working fine.

Screenshot from 2024-02-27 22-07-26

Screenshot from 2024-02-27 22-07-21

**Review by benjagm — CHANGES_REQUESTED** [review]
Thanks @aialok! I managed tested in my fork and now I am getting this error:

https://github.com/benjagm/community/actions/runs/8082430183/job/22083253583

**Comment by aialok** [comment]
> Thanks @aialok! I managed tested in my fork and now I am getting this error:
> 
> https://github.com/benjagm/community/actions/runs/8082430183/job/22083253583
> 
> Screenshot 2024-02-28 at 16 05 02
> I think it is because this:
> 
> ```
>       with:
>         script: |
>         
>           import { Octokit } from "@octokit/core";
> ```

Basically I run my own script in node environment with esm but It seems like it is using common js module. I will be fixing this in a while.

**Comment by aialok** [comment]
Basically right now `actions/github-script` does not support es module. I am planning to write a script in es module in separate file and run this script from github-actions.
This way our work will be done and we will be using latest version of `octokit/core`.
Otherwise, we will need to use version 5.1.0

@benjagm , which one way should I go with  separate script file or roll back to older version.

**Comment by utnim2** [comment]
> > I think it is because this:
> > ```
> >       with:
> >         script: |
> >         
> >           import { Octokit } from "@octokit/core";
> > ```
> 
> Basically I run my own script in node environment with esm but It seems like it is using common js module. I will be fixing this in a while.

you can always write
```bash
const octokit=require('@octokit/core')
```

**Comment by princerajpoot20** [comment]
I am in favor of using the older, stable version, which is v5.1.0. This way, we will avoid these types of issues in the future, and this v5 version fulfills all the requirements we need.
cc: @benjagm @aialok Thoughts?

**Comment by aialok** [comment]
> I am in favor of using the older, stable version, which is v5.1.0. This way, we will avoid these types of issues in the future, and this v5 version fulfills all the requirements we need. cc: @benjagm @aialok Thoughts?

Yes, we can go with this.
Well I have created issue for support of esm module in `github-scripts` if it get solve then we will update it later. 
Till then this is good to go.

**Comment by benjagm** [comment]
Let's use the older version of octokit/core.js  package for now.

**Comment by benjagm** [comment]
@aialok I tested the code and I am getting this error:

https://github.com/benjagm/community/actions/runs/8110471278/job/22167791676

**Comment by benjagm** [comment]
> @aialok I tested the code and I am getting this error:
> 
> https://github.com/benjagm/community/actions/runs/8110471278/job/22167791676

Let me check again. I think is my dev setup.

**Comment by benjagm** [comment]
It works.

**Review by benjagm — APPROVED** [review]

**Pull request merged**
