### PR TITLE
fix: open community working meeting failed

### LINKED ISSUE #644: [Bug] Action to to create Open Community Working Meeting failed
Work Summary:
The github action used to create Open Community Working Meeting failed today:

See issue #640 . Issue is the same.

Error: https://github.com/json-schema-org/community/actions/runs/8062344014

Do you think this work might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)

No

### PR DESCRIPTION
**Pull request by princerajpoot20**
**GitHub Issue:** #644 
Resolves #644 

**Summary**:

**Do you think resolving this issue might require an [Architectural Decision Record (ADR)](https://github.com/json-schema-org/community/blob/main/CONTRIBUTING.md#key-architectural-decisions)? (significant or noteworthy)**

Yes/No
[No] It is a bug fix

### CODE REVIEW

**Comment by princerajpoot20** [comment]
I have analyzed the error we are facing:
```
error: create-issue
Unhandled error: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /home/runner/work/CI-CD-Testing/CI-CD-Testing/node_modules/@octokit/core/package.json
``` 
It indicates that the error is coming from the octokit's package.json file. I have checked their [GitHub repo](https://github.com/octokit/core.js/), and they have released their next major version (v6) three days ago. Here is the [link to that](https://github.com/octokit/core.js/releases). So, there must be some compatibility issues with this new version.

I have tried using the previous stable version, which is **5.1.0**, and this error got resolved. Though I am now encountering a different error due to Slack URL and environment variables, but the original octokit error seems to have vanished with this.

cc: @benjagm

**Comment by aialok** [comment]
> I have analyzed the error we are facing:
> 
> ```
> error: create-issue
> Unhandled error: Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /home/runner/work/CI-CD-Testing/CI-CD-Testing/node_modules/@octokit/core/package.json
> ```
> 
> It indicates that the error is coming from the octokit's package.json file. I have checked their [GitHub repo](https://github.com/octokit/core.js/), and they have released their next major version (v6) three days ago. Here is the [link to that](https://github.com/octokit/core.js/releases). So, there must be some compatibility issues with this new version.
> 
> I have tried using the previous stable version, which is **5.1.0**, and this error got resolved. Though I am now encountering a different error due to Slack URL and environment variables, but the original octokit error seems to have vanished with this.
> 
> cc: @benjagm


Hey @princerajpoot20! I'm also working on a similar issue. The latest release of octokit/code.js has changed its entire codebase from CommonJS modules to ES modules (ESM), causing errors when using `require`. While we can use the latest version of octokit, the problem lies in not being able to use import in GitHub Actions because `actions/github-script` only supports scripts in CommonJS.

I'm currently checking the documentation and various resources to find a solution. If you have any ideas on how to use ESM in GitHub Actions, I'd appreciate your input. If I find a solution, I'll share it with you. Otherwise, I may have to revert to version 5.1.0.

Thank You : )

**Comment by princerajpoot20** [comment]
@aialok As of now, I have tested the approach you used in #647 . ([run link](https://github.com/princerajpoot20/CI-CD-Testing/actions/runs/8086778825)) . However, it is causing an error: ``` Unhandled error: SyntaxError: Cannot use import statement outside a module ```
As you have already mentioned, the problem lies in the inability to use import in GitHub Actions because actions/github-script only supports scripts in CommonJS format. 
I will review some more documentation and share an update with you if I find something relevant.

**Comment by aialok** [comment]
> @aialok As of now, I have also tested the approach you used in #647 . ([run link](https://github.com/princerajpoot20/CI-CD-Testing/actions/runs/8086778825)) .
> 
> However, it is causing an error: `Unhandled error: SyntaxError: Cannot use import statement outside a module` As you have already mentioned, the problem lies in the inability to use import in GitHub Actions because actions/github-script only supports scripts in CommonJS format.
> 
> I will review some more documentation and share an update with you if I find something relevant.

Thank you @princerajpoot20, I am also working on this : )

**Comment by benjagm** [comment]
Let's use the older version of octokit/core.js  package for now.

**Comment by princerajpoot20** [comment]
> Let's use the older version of octokit/core.js package for now.

@benjagm Done 🙂

**Review by benjagm — CHANGES_REQUESTED** [review]
Thanks! This works. I am getting this warning:
````
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v2, actions/setup-node@v2, actions/github-script@v6. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
````

Can we use this same PR to upgrade to node 20 and version of actions? You can see other workflows to validate how we did it in other cases.

**Review by benjagm — APPROVED** [review]

**Pull request merged**
