### PR TITLE
applying for ambassadors at JSONschema

### PR DESCRIPTION
**Pull request by Estherokafor05**
Additional article i wrote on  test sigma - https://testsigma.com/blog/schema-validation-in-api-testing/

### CODE REVIEW

**Review by benjagm — COMMENTED** [review]
Hi @Estherokafor05 ! Thanks a lot for your interest and your work in Storyblok. The Ambassadors Program is targeting mainly JSON Schema experts with a solid track record of JSON Schema contributions and this is why we'll like to know if you have some more JSON Schema content that we can check before consider your application.

Thanks a lot!

**Comment by Esthertests** [comment]
> Hi @Estherokafor05 ! Thanks a lot for your interest and your work in Storyblok. The Ambassadors Program is targeting mainly JSON Schema experts with a solid track record of JSON Schema contributions and this is why we'll like to know if you have some more JSON Schema content that we can check before consider your application.
> 
> Thanks a lot!

Hi @benjagm I have this other one published [blog](https://estherokafor.com/beyond-assertions-data-validation-using-cypress-with-json-schema-in-end-to-end-testing). My focus is to contribute to documentation on how JSON schema is helpful in data integrity with testing. I hope to write about this using different testing tools like Playwright, selenium, TestNG and other mobile automation tools. let me know if you need anything more. Thank you

**Comment by benjagm** [comment]
Hi Esther, As discussed please update the PR with 2 more contributions and well progress with the review and approval. Thanks a lot!

**Review by Estherokafor05 — COMMENTED** [review]
Hi @benjagm I will like to Inform you that my slides for the speaking engagement where I will also be discussing the benefits of JSON SCHEMA in API design for [API CONF](https://www.linkedin.com/company/api-conf-lagos/) on API [design](https://www.canva.com/design/DAGJgnhNUYA/GLVTP-Yx7wcBVFjOhsN2uQ/edit?utm_content=DAGJgnhNUYA&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton) is ready. 
Also I have written another article which was featured in  [227th issue of Software Testing Weekly ](https://www.linkedin.com/posts/okaforesther_softwaretestingweekly-softwaretesting-testautomation-activity-7216343077764878337-0Nv9?utm_source=share&utm_medium=member_desktop) 

The announcement of my speaking was posted this morning on [Linkedin here ](https://www.linkedin.com/posts/api-conf-lagos_apiconflagos-techconference-apidevelopment-activity-7217862207642976256-O7b9?utm_source=share&utm_medium=member_desktop).  Please let me know if you need more information.

**Comment by benjagm** [comment]
Can you please fix the merge conflict?

**Comment by Esthertests** [comment]
> Can you please fix the merge conflict?

fixed

**Review by benjagm — CHANGES_REQUESTED** [review]
Hi Esther. I just realized that instead of adding a new json entry you are replacing an existing entry belonging to another ambassador, Andreas Eberhart. Can you please modify the PR? I'll approve right away.

**Comment by Esthertests** [comment]
> Hi Esther. I just realized that instead of adding a new json entry you are replacing an existing entry belonging to another ambassador, Andreas Eberhart. Can you please modify the PR? I'll approve right away.

Hello @benjagm thanks for s;potting, I have fixed the files now

**Review by benjagm — APPROVED** [review]
Thanks for applying Esther! Looks good to me.

**Pull request merged**
